### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by qiilee** [EasyTuan/taro-msparis#30]
**问题描述**
[问题描述：无法安装项目依赖]

**复现步骤**
[复现问题的步骤]
1. git clone https://github.com/EasyTuan/taro-msparis.git
2. cd taro-msparis
3. npm install

**期望行为**
[安装成功]

**报错信息**

[Unhandled rejection RangeError: Maximum call stack size exceeded
    at RegExp.test (<anonymous>)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\aproba\index.js:38:16
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\aproba\index.js:33:11)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:37:3)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-12-18T02_08_38_750Z-debug.log]

**系统信息**

 - 操作系统: [e.g. Windows 10]
 - Taro 版本 [Taro v1.2.0-beta.16]
 - Node.js 版本 [e.g. v8.12.0]
 - npm版本 [6.5.0]

**补充信息**
[百度是：超过最大调用栈问题；给npm降级到5.4.0或者升级到6.5.0 都没解决问题]

**Comment by qiilee** [comment]
问题已解决，我试了下cnpm i 命令可以安装成功！[cnpm@6.0.0]

**Comment by EasyTuan** [comment]
好的
